services:
  db:
    image: postgres:latest
    container_name: assessment-sigmatech
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB?Variable not set}
      POSTGRES_USER: ${POSTGRES_USER?Variable not set}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD?Variable not set}
      TZ: "Asia/Jakarta"
    ports:
      - ${POSTGRES_DB_EXPOSE_PORT?Variable not set}:${POSTGRES_DB_PORT?Variable not set}
    networks:
      - sigmatech-network
    volumes:
      - postgre_data:/var/lib/postgresql/data
      - ./data/postgres:/docker-entrypoint-initdb.d
  svc-sigmatech:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: svc-sigmatech
    ports:
      -  ${SVC_PORT?Variable not set}:${SVC_PORT?Variable not set}
      - 40000:40000 
    networks:
      - sigmatech-network
    volumes:
      - ./:/app
  minio-sigmatech:
    image: minio/minio
    container_name: minio-sigmatech
    ports:
      - '${MINIO_API_PORT?Variable not set}:9000'
      - '${MINIO_CONSOLE_PORT?Variable not set}:9001'
    networks:
      - sigmatech-network 
    volumes:
      - assessment-sigmatech-minio-data:/data
      - ./init-minio.sh:/init-minio.sh  
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER?Variable not set}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD?Variable not set}
      - MINIO_DEFAULT_BUCKETS=${MINIO_BUCKET?Variable not set}
    command: 
      - /bin/sh
      - -c
      - |
        /opt/minio/bin/minio server /data --address :${MINIO_API_PORT?Variable not set} --console-address :${MINIO_CONSOLE_PORT?Variable not set} & 
        sleep 10
        chmod +x /init-minio.sh
        /init-minio.sh
        wait

volumes:
  postgre_data:
    name: assessment-sigmatech-data
    external: true
  assessment-sigmatech-minio-data:
    name: assessment-sigmatech-minio-data
    external: true


networks:
  sigmatech-network:
    name: sigmatech-network
    driver: bridge
  
  