services:
  db:
    image: postgres:latest
    container_name: assessment-sigmatech
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB?Variable not set}
      POSTGRES_USER: ${POSTGRES_USER?Variable not set}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD?Variable not set}
      TZ: "Asia/Jakarta"
    ports:
      - ${POSTGRES_DB_EXPOSE_PORT?Variable not set}:${POSTGRES_DB_PORT?Variable not set}
    networks:
      - sigmatech-network
    volumes:
      - postgre_data:/var/lib/postgresql/data
      - ./data/postgres:/docker-entrypoint-initdb.d
  svc-sigmatech:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: svc-sigmatech
    ports:
      -  ${SVC_PORT?Variable not set}:${SVC_PORT?Variable not set}
      - 40000:40000 
    networks:
      - sigmatech-network
    volumes:
      - ./:/app
  minio:
    image: minio/minio
    ports:
      - '${MINIO_API_PORT?Variable not set}:9000'
      - '${MINIO_CONSOLE_PORT?Variable not set}:9001'
    networks:
      - sigmatech-network 
    volumes:
      - assessment-sigmatech-minio-data:/data
      -  ./config/minio-config:/config
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER?Variable not set}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD?Variable not set}
      - MINIO_DEFAULT_BUCKETS=${MINIO_BUCKET?Variable not set}
    command: server /data --console-address ":${MINIO_CONSOLE_PORT}"

volumes:
  postgre_data:
    name: assessment-sigmatech-data
    external: true
  assessment-sigmatech-minio-data:
    name: assessment-sigmatech-minio-data
    external: true

networks:
  sigmatech-network:
    name: sigmatech-network
  
  